boards: use littlefs for parameter storage
Co-authored-by: Igor Mišić <igy1000mb@gmail.com>
Co-authored-by: Daniel Agar <daniel@agar.ca>

diff --git a/ROMFS/px4fmu_common/init.d/rcS b/ROMFS/px4fmu_common/init.d/rcS
--- a/ROMFS/px4fmu_common/init.d/rcS
+++ b/ROMFS/px4fmu_common/init.d/rcS
@@ -112,7 +112,21 @@ else
 	#
 	if mft query -q -k MTD -s MTD_PARAMETERS -v /fs/mtd_params
 	then
-		set PARAM_FILE /fs/mtd_params
+		set PARAM_FILE /fs/mtd_params/parameters.bson
+	else
+		# TODO: This code shall be reverted after the BCH->LittleFS param transition time is completed
+		set PARAM_FILE /fs/mtd_params/parameters.bson
+		param select $PARAM_FILE
+		echo "Start parameter transition to LittleFS"
+		if ! param transition
+		then
+			echo "ERROR [init] param transition"
+		else
+			echo "The system will reboot!"
+			# Wait for UART to send messages
+			usleep 200000
+			reboot
+		fi
 	fi
 
 	#
