[FREEFLY] rcS: Magnetometer calibration transition mechanisms
rcS: transition factory calibration mag rotation from 23 to 43

Signed-off-by: Claudio Micheli <claudio@auterion.com>

Remove old mag cals from eeprom

Reset mag calibration only if the parameter version is too old

So far, the mag cal is always reset when the current parameter version and the default version from the airframe configuration don't match. This means, the vehicle has to be often calibrated after a software update, even though, the calibration would still be valid.
With the new logic, the calibration is only reset if the parameter version is too old. 61 was the parameter default version in release v1.0.22. The sensor coordinate system in one of the mag drivers has changed in the next release and thus, we still have to reset the incompatible calibration.

Changed threshold for resetting mag cal to all versions before 1.1.11

diff --git a/ROMFS/px4fmu_common/init.d/rcS b/ROMFS/px4fmu_common/init.d/rcS
--- a/ROMFS/px4fmu_common/init.d/rcS
+++ b/ROMFS/px4fmu_common/init.d/rcS
@@ -195,6 +195,31 @@ else
 		param load /fs/mtd_caldata
 	fi
 
+	# FREEFLY CUSTOM: factory calibration: rotation param update.
+	# Can be removed after all vehicles are migrated to a release > 2.1
+	if param compare CAL_MAG1_ROT 23
+	then
+		echo "Updating factory rotation param CAL_MAG1_ROT"
+		param set CAL_MAG1_ROT 43
+		param save /fs/mtd_caldata
+	fi
+
+	# FREEFLY CUSTOM: factory calibration: remove old mag cals
+	# If the airframe has an old mag cal, remove it from eeprom to avoid chance of resetting params and getting values from EEPROM
+	# logic: If CAL_MAG0_XOFF is not zero (thus has a stored mag cal of any type), but does NOT have a
+	# nonzero CAL_MAG0_XODIAG (thus is an old mag cal), wipe ALL CAL_MAG* params from EEPROM and save
+	#
+	if ! param compare CAL_MAG0_XOFF 0
+	then
+		if param compare CAL_MAG0_XODIAG 0
+		then
+			echo "old magcal detected in eeprom, removing"
+			param reset CAL_MAG*
+			param save /fs/mtd_caldata
+		fi
+	fi
+
+
 	param select $PARAM_FILE
 	if ! param import
 	then
@@ -310,6 +335,13 @@ else
 	# Reboot required because "param reset_all" would reset all "param set" lines from airframe.
 	if ! param compare SYS_PARAM_VER ${PARAM_DEFAULTS_VER}
 	then
+		# FREEFLY CUSTOM
+		if ! param greater SYS_PARAM_VER 72
+		then
+			echo "Parameter version older than 73 for 1.1.11. Resetting mag calibration."
+			param reset CAL_MAG0* CAL_MAG1*
+		fi
+
 		echo "Switched to different parameter version. Resetting parameters."
 		param set SYS_PARAM_VER ${PARAM_DEFAULTS_VER}
 		param set SYS_AUTOCONFIG 1
