Parameter reverse transition from LittleFS to block device
For the smooth backward transition from LittleFS to preserve parameters

diff --git a/ROMFS/px4fmu_common/init.d/rcS b/ROMFS/px4fmu_common/init.d/rcS
--- a/ROMFS/px4fmu_common/init.d/rcS
+++ b/ROMFS/px4fmu_common/init.d/rcS
@@ -141,6 +141,18 @@ else
 	param select $PARAM_FILE
 	if ! param import
 	then
+
+		echo "Try parameter reverse transition from LittleFS"
+		if ! param transition
+		then
+			echo "ERROR [init] param transition"
+		else
+			echo "Successful param reverse transition. The system will reboot!"
+			# Wait for UART to send messages
+			usleep 200000
+			reboot
+		fi
+
 		echo "ERROR [init] param import failed"
 		set STARTUP_TUNE 2 # tune 2 = ERROR_TUNE
 
