Changes to get a clean compile with the Kconfig Shenzhou board.  Still some link issues
git-svn-id: https://nuttx.svn.sourceforge.net/svnroot/nuttx/trunk@5115 7fd9a85b-ad96-42d3-883c-3090e2eb8679

diff --git a/nuttx/Makefile b/nuttx/Makefile
--- a/nuttx/Makefile
+++ b/nuttx/Makefile
@@ -616,9 +616,10 @@ endif
 # apps_clean:     Perform the clean operation only in the user application
 #                 directory
 # apps_distclean: Perform the distclean operation only in the user application
-#                 directory.  Note that the apps/.config file is preserved
-#                 so that this is not a "full" distclean but more of a
-#                 configuration "reset."
+#                 directory.  Note that the apps/.config file (inf any) is
+#                 preserved so that this is not a "full" distclean but more of a
+#                 configuration "reset." (There willnot be an apps/.config
+#                 file if the configuration was generated via make menuconfig).
 
 apps_clean:
 ifneq ($(APPDIR),)
@@ -627,10 +628,16 @@ endif
 
 apps_distclean:
 ifneq ($(APPDIR),)
-	@cp "$(TOPDIR)/$(APPDIR)/.config" _SAVED_APPS_config || \
-		{ echo "Copy of $(APPDIR)/.config failed" ; exit 1 ; }
+	@if [ -r "$(TOPDIR)/$(APPDIR)/.config" ]; then \
+		cp "$(TOPDIR)/$(APPDIR)/.config" _SAVED_APPS_config || \
+			{ echo "Copy of $(APPDIR)/.config failed" ; exit 1 ; } \
+	else \
+		rm -f _SAVED_APPS_config; \
+	fi
 	@$(MAKE) -C "$(TOPDIR)/$(APPDIR)" TOPDIR="$(TOPDIR)" distclean
-	@mv _SAVED_APPS_config "$(TOPDIR)/$(APPDIR)/.config" || \
-		{ echo "Copy of _SAVED_APPS_config failed" ; exit 1 ; }
+	@if [ -r _SAVED_APPS_config ]; then \
+		@mv _SAVED_APPS_config "$(TOPDIR)/$(APPDIR)/.config" || \
+			{ echo "Copy of _SAVED_APPS_config failed" ; exit 1 ; } \
+	fi
 endif
 
