Moved from OLD and NEW M0065_SBUS to doing an autodetect on which version it may have

diff --git a/boards/modalai/voxl2/target/voxl-px4-start b/boards/modalai/voxl2/target/voxl-px4-start
--- a/boards/modalai/voxl2/target/voxl-px4-start
+++ b/boards/modalai/voxl2/target/voxl-px4-start
@@ -114,7 +114,7 @@ if [ "$ESC" == "VOXL_ESC" ]; then
     /bin/echo "Starting VOXL ESC driver"
 	qshell voxl_esc start
 elif [ "$ESC" == "VOXL2_IO_PWM_ESC" ]; then
-	if [ "$RC" == "NEW_M0065_SBUS" ]; then
+	if [ "$RC" == "M0065_SBUS" ]; then
 		/bin/echo "Starting VOXL IO for PWM ESC with SBUS RC"
 		qshell voxl2_io start
 	else
@@ -136,9 +136,6 @@ elif [ "$RC" == "CRSF_RAW" ]; then
 elif [ "$RC" == "CRSF_MAV" ]; then
     /bin/echo "Starting TBS crossfire RC - MAV Mode"
     qshell mavlink_rc_in start -m -p 7 -b 115200
-elif [ "$RC" == "OLD_M0065_SBUS" ]; then
-    /bin/echo "Starting M0065 SBUS RC driver for original M0065 FW"
-    qshell dsp_sbus start
 elif [ "$RC" == "SPEKTRUM" ]; then
     /bin/echo "Starting Spektrum RC"
 	# On M0052 the RC driver runs on the apps processor
@@ -151,10 +148,16 @@ elif [ "$RC" == "SPEKTRUM" ]; then
 elif [ "$RC" == "GHST" ]; then
     /bin/echo "Starting GHST RC driver"
     qshell ghst_rc start -d 7
-elif [ "$RC" == "NEW_M0065_SBUS" ]; then
-	if [ "$ESC" == "VOXL_ESC" ]; then
-    	/bin/echo "Starting M0065 SBUS RC driver for current M0065 FW"
-		qshell voxl2_io start -d -p 7
+elif [ "$RC" == "M0065_SBUS" ]; then
+	if [ "$ESC" != "VOXL2_IO_PWM_ESC" ]; then
+    	/bin/echo "Attempting to start M0065 SBUS RC driver for original M0065 FW"
+    	qshell dsp_sbus start
+		retVal=$?
+		if [ $retVal -ne 0 ]; then
+	    	/bin/echo "Starting M0065 SBUS RC driver for original M0065 FW failed"
+	    	/bin/echo "Attempting to start M0065 SBUS RC driver for new M0065 FW"
+			qshell voxl2_io start -d -p 7
+		fi
 	else
     	/bin/echo "M0065 SBUS RC driver already started with PWM ESC start"
 	fi
