filtering files for code check seperately to enable fast use of git pre-commit hook to check code style ask user to install pre-commit hook when code style is checked

diff --git a/Tools/pre-commit b/Tools/pre-commit
--- a/Tools/pre-commit
+++ b/Tools/pre-commit
@@ -1,26 +1,64 @@
 #!/bin/sh
+#
+# An example hook script to verify what is about to be committed.
+# Called by "git commit" with no arguments.  The hook should
+# exit with non-zero status after issuing an appropriate message if
+# it wants to stop the commit.
+#
+# To enable this hook, rename this file to "pre-commit".
+
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
-  against=HEAD
+	against=HEAD
 else
-  # Initial commit: diff against an empty tree object
-  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+	# Initial commit: diff against an empty tree object
+	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
+
+# If you want to allow non-ascii filenames set this variable to true.
+allownonascii=$(git config hooks.allownonascii)
 
 # Redirect output to stderr.
 exec 1>&2
 
-CHANGED_FILES=`git diff --cached --name-only --diff-filter=ACM $against | grep '\.c\|\.cpp\|\.h\|\.hpp'`
-FAILED=0
-if [ ! -z "$CHANGED_FILES" -a "$CHANGED_FILES" != " " ]; then
-  for FILE in $CHANGED_FILES; do
-    ./Tools/fix_code_style.sh --quiet < $FILE > $FILE.pretty
-    diff -u $FILE $FILE.pretty || FAILED=1
-    rm -f $FILE.pretty
-    if [ $FAILED -ne 0 ]; then
-      echo "There are code formatting errors. Please fix them by running ./Tools/fix_code_style.sh $FILE"
-      exit $FAILED
-    fi
-  done
+# Cross platform projects tend to avoid non-ascii filenames; prevent
+# them from being added to the repository. We exploit the fact that the
+# printable range starts at the space character and ends with tilde.
+if [ "$allownonascii" != "true" ] &&
+	# Note that the use of brackets around a tr range is ok here, (it's
+	# even required, for portability to Solaris 10's /usr/bin/tr), since
+	# the square bracket bytes happen to fall in the designated range.
+	test $(git diff --cached --name-only --diff-filter=A -z $against |
+	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+then
+	echo "Error: Attempt to add a non-ascii file name."
+	echo
+	echo "This can cause problems if you want to work"
+	echo "with people on other platforms."
+	echo
+	echo "To be portable it is advisable to rename the file ..."
+	echo
+	echo "If you know what you are doing you can disable this"
+	echo "check using:"
+	echo
+	echo "  git config hooks.allownonascii true"
+	echo
+	exit 1
 fi
-exit 0
+
+# If there are whitespace errors, print the offending file names and fail.
+git diff-index --check --cached $against --
+if [ $? -ne 0 ]
+then
+        exit 1
+fi
+
+# Check for code style, only in changed files
+for i in `git diff --cached --name-only --diff-filter=ACM`
+do
+        ./Tools/files_to_check_code_style.sh $i | xargs -n 1 -P 8 -I % ./Tools/check_code_style.sh %
+        if [ $? -ne 0 ]
+        then
+                exit 1
+        fi
+done
